// <auto-generated />
using System;
using AdministracionMasVidaDbContext.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdministracionMasVida.Migrations
{
    [DbContext(typeof(AdministracionMasVidaDbcontext))]
    [Migration("20231115023621_InitialDataBase")]
    partial class InitialDataBase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AdministracionMasVidaDbContext.Entities.GrupoPequeno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Dia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HoraFin")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HoraInico")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("MentorId")
                        .HasColumnType("int");

                    b.Property<int>("MentorId1")
                        .HasColumnType("int");

                    b.Property<string>("NombreGrupo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("MentorId");

                    b.HasIndex("MentorId1");

                    b.ToTable("GrupoPequeno");
                });

            modelBuilder.Entity("AdministracionMasVidaDbContext.Entities.Mentor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Mentor");
                });

            modelBuilder.Entity("AdministracionMasVidaDbContext.Entities.Miembro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Miembro");
                });

            modelBuilder.Entity("AdministracionMasVidaDbContext.Entities.Servidor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("LiderGrupoId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("LiderGrupoId");

                    b.ToTable("Servidor");
                });

            modelBuilder.Entity("GrupoPequenoMiembro", b =>
                {
                    b.Property<int>("MiembroId")
                        .HasColumnType("int");

                    b.Property<int>("grupoPequenosId")
                        .HasColumnType("int");

                    b.HasKey("MiembroId", "grupoPequenosId");

                    b.HasIndex("grupoPequenosId");

                    b.ToTable("GrupoPequenoMiembro");
                });

            modelBuilder.Entity("AdministracionMasVidaDbContext.Entities.GrupoPequeno", b =>
                {
                    b.HasOne("AdministracionMasVidaDbContext.Entities.Mentor", null)
                        .WithMany("grupoPequenos")
                        .HasForeignKey("MentorId");

                    b.HasOne("AdministracionMasVidaDbContext.Entities.Servidor", "Mentor")
                        .WithMany("MentorGrupos")
                        .HasForeignKey("MentorId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mentor");
                });

            modelBuilder.Entity("AdministracionMasVidaDbContext.Entities.Servidor", b =>
                {
                    b.HasOne("AdministracionMasVidaDbContext.Entities.GrupoPequeno", "LiderGrupo")
                        .WithMany("Lideres")
                        .HasForeignKey("LiderGrupoId");

                    b.Navigation("LiderGrupo");
                });

            modelBuilder.Entity("GrupoPequenoMiembro", b =>
                {
                    b.HasOne("AdministracionMasVidaDbContext.Entities.Miembro", null)
                        .WithMany()
                        .HasForeignKey("MiembroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdministracionMasVidaDbContext.Entities.GrupoPequeno", null)
                        .WithMany()
                        .HasForeignKey("grupoPequenosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AdministracionMasVidaDbContext.Entities.GrupoPequeno", b =>
                {
                    b.Navigation("Lideres");
                });

            modelBuilder.Entity("AdministracionMasVidaDbContext.Entities.Mentor", b =>
                {
                    b.Navigation("grupoPequenos");
                });

            modelBuilder.Entity("AdministracionMasVidaDbContext.Entities.Servidor", b =>
                {
                    b.Navigation("MentorGrupos");
                });
#pragma warning restore 612, 618
        }
    }
}
