// <auto-generated />
using System;
using AdministracionMasVidaDbContext.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdministracionMasVida.Migrations
{
    [DbContext(typeof(AdministracionMasVidaDbcontext))]
    [Migration("20240103215116_migrationsmv")]
    partial class migrationsmv
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AdministracionMasVida.Entities.EventosMv", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Grupo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Hora")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Lugar")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("EventosMv");
                });

            modelBuilder.Entity("AdministracionMasVida.Entities.LugaresMv", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Precio")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("LugaresMv");
                });

            modelBuilder.Entity("AdministracionMasVidaDbContext.Entities.GrupoPequeno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Dia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HoraFin")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HoraInicio")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("MentorId")
                        .HasColumnType("int");

                    b.Property<string>("NombreGrupo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("MentorId");

                    b.ToTable("GrupoPequeno");
                });

            modelBuilder.Entity("AdministracionMasVidaDbContext.Entities.Miembro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("grupoPequenosId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("grupoPequenosId");

                    b.ToTable("Miembro");
                });

            modelBuilder.Entity("AdministracionMasVidaDbContext.Entities.Servidor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("LiderGrupoId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("LiderGrupoId");

                    b.ToTable("Servidor");
                });

            modelBuilder.Entity("EventosMvLugaresMv", b =>
                {
                    b.Property<int>("EventoId")
                        .HasColumnType("int");

                    b.Property<int>("LugaresId")
                        .HasColumnType("int");

                    b.HasKey("EventoId", "LugaresId");

                    b.HasIndex("LugaresId");

                    b.ToTable("EventosMvLugaresMv");
                });

            modelBuilder.Entity("AdministracionMasVidaDbContext.Entities.GrupoPequeno", b =>
                {
                    b.HasOne("AdministracionMasVidaDbContext.Entities.Servidor", "Mentor")
                        .WithMany("MentorGrupos")
                        .HasForeignKey("MentorId");

                    b.Navigation("Mentor");
                });

            modelBuilder.Entity("AdministracionMasVidaDbContext.Entities.Miembro", b =>
                {
                    b.HasOne("AdministracionMasVidaDbContext.Entities.GrupoPequeno", "grupoPequenos")
                        .WithMany("Miembro")
                        .HasForeignKey("grupoPequenosId");

                    b.Navigation("grupoPequenos");
                });

            modelBuilder.Entity("AdministracionMasVidaDbContext.Entities.Servidor", b =>
                {
                    b.HasOne("AdministracionMasVidaDbContext.Entities.GrupoPequeno", "LiderGrupo")
                        .WithMany("Lideres")
                        .HasForeignKey("LiderGrupoId");

                    b.Navigation("LiderGrupo");
                });

            modelBuilder.Entity("EventosMvLugaresMv", b =>
                {
                    b.HasOne("AdministracionMasVida.Entities.EventosMv", null)
                        .WithMany()
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdministracionMasVida.Entities.LugaresMv", null)
                        .WithMany()
                        .HasForeignKey("LugaresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AdministracionMasVidaDbContext.Entities.GrupoPequeno", b =>
                {
                    b.Navigation("Lideres");

                    b.Navigation("Miembro");
                });

            modelBuilder.Entity("AdministracionMasVidaDbContext.Entities.Servidor", b =>
                {
                    b.Navigation("MentorGrupos");
                });
#pragma warning restore 612, 618
        }
    }
}
